### PR TITLE
Adding clickable buttons that can give us a star

### PR DESCRIPTION
**Pull request by Jiri-Kremser**
Well, it's still needed to click on the star on the github page. There is also option to show the star counter.

screenshot-20171013153823-1920x1046

### CODE REVIEW

**Comment by elmiko** [comment]
very cool! thanks Jirka

**Comment by elmiko** [comment]
@mattf ptal, curious for your thoughts

**Comment by mattf** [comment]
lgtm, i'd also +1 watch & fork buttons

**Comment by elmiko** [comment]
i'd be good with adding those extra buttons if we could figure out how to do those actions. currently the star button just takes you to the landing page for the project, so i'm little hesitant to just add more links that all go to the project page.

**Comment by Jiri-Kremser** [comment]
> i'd be good with adding those extra buttons if we could figure out how to do those actions. 

I think it's currently not possible to directly fork/watch/star a repo from external site. It was, but they changed the behavior, probably because people were misusing it.

**Comment by elmiko** [comment]
gotcha, well i'm cool with leaving the star buttons but i don't think we should add the other unless github changes their policies

**Comment by Jiri-Kremser** [comment]
:+1: it's pretty standard as it is and openshift.org has it the same way

**Comment by elmiko** [comment]
cool, thanks for extra details

**Pull request merged**
