### PR TITLE
upgrade dockerfile

### PR DESCRIPTION
**Pull request by elmiko**
This change upgrades the dockerfile to no longer require the jekyll
base. As the site moves further away from standard jekyll deploys, the
upstream image has proven more difficult to work with. This change bases
the image off a fedora base and installs the necessary requirements.

### CODE REVIEW

**Comment by elmiko** [comment]
closes #142 

@crobby ptal

**Comment by elmiko** [comment]
just to add some data, here is the timing effect from using a base image as opposed to building the whole thing.

*base image timing*
```
real    0m32.739s
user    0m0.132s
sys     0m0.070s
```

*full image timing*
```
real    3m11.209s
user    0m0.185s
sys     0m0.111s
```

so, if that 2:45 minute speed up is worth it, i can push the images for a base and make this a little snappier for devs. seems like it could be worth the upgrade especially when rebuilding the site multiple times.

**Comment by crobby** [comment]
The speedup idea is nice, even if I'm the only one who uses it that way.  +1 as long as it's something super quick and easy to do.

**Comment by elmiko** [comment]
ok, i'll push the image and adjust the pr. thanks!

**Comment by crobby** [comment]
still lgtm

**Comment by elmiko** [comment]
ok, i'm gonna merge. thanks Chad!

**Pull request merged**
