### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by mattf**
@elmiko ptal

### CODE REVIEW

**Comment by elmiko** [comment]
i've been writing something similar, i think we could merge both of them together though.

**Comment by mattf** [comment]
ok, shall i close this?

**Comment by elmiko** [comment]
no, i think i'll merge this tomorrow and then work my material in on top of it. this is good, i have a few additional screenshoft and some extra descriptions. i also incorporate the oshinko-webui instructions here into the upstream docs.

i think both our content will be very complimentary, thanks!

**Comment by elmiko** [comment]
thanks Matt!

**Pull request merged**
