### PR TITLE
Add the pyspark-hdfs-notebook example

### PR DESCRIPTION
**Pull request by tmckayus**
This example shows how to read an HDFS file from a remote
Hadoop cluster from PySpark.

### CODE REVIEW

**Comment by elmiko** [comment]
i tested this on et0 and it worked well for me, i have a couple nits

1. the Video section has nothing in it, in the other tutorials with no video we have a sentence like "There is no video for this tutorial currently" in that section. i'd like to follow that pattern.

1. the slidedeck still has the example template stuff in it, at the least we should remove that and fill out the 2 slides.

**Comment by tmckayus** [comment]
Note, this is a first pass with an unsecured HDFS.  As a second pass, it would be great to add an example where Spark reads from a secured HDFS, and maybe add writes back (writes seemed to hang for some reason after creating an empty output directory when I iniitally tried it)

**Comment by elmiko** [comment]
+1 on the update Trevor, just add a quick slide deck and we can get this one merged =)

**Comment by tmckayus** [comment]
bah, I wrote the wrong lightning file :)

**Comment by elmiko** [comment]
thanks for adding the changes Trevor!

**Pull request merged**
