### PR TITLE
add s3 source example as an "application"

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by mattf** [comment]
@elmiko ptal

**Comment by elmiko** [comment]
this looks good, gonna test the instructions locally

**Comment by elmiko** [comment]
any reason for using `rc/workshop-1` over `dc/workshop` in the logs query?

**Comment by elmiko** [comment]
these instructions mostly worked for me. i could not get the `oc logs rc/workshop-1` to work though, it did work if i used `dc/workshop`

**Comment by mattf** [comment]
before the app starts getting the logs of the dc only returns terse information about the deployment process. the rc should redirect to the pod logs.

i just tried dc/workshop w/ a fully deployed workshop image and it worked. so i updated the instructions.

**Comment by elmiko** [comment]
cool, thanks for the update

**Pull request merged**
