### PR TITLE
APP_EXIT=true by default and use oc edit dc/your-app and change it to false to enable debugging

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by mattf** [comment]
@tmckayus ptal

**Comment by elmiko** [comment]
i don't have an objection to this, but i'm curious what Trevor thinks.

**Comment by tmckayus** [comment]
It means that in the default case dc usage for one-off batch jobs doesn't fit.  For that case you'll want to use a job, and if you want to use a job then most likely we should add the pyspark-build-job template back in (had one of these once upon a time). While we're waiting for trigger support, it will throw errors waiting for the build (bah!) but better than recalculating Pi forever imho :)

Will test and verify

**Comment by tmckayus** [comment]
Will also mean that when we make the requested READMEs for template usage, we should include a section on when to use dc, when to use job, expected behavior, and workarounds (oc edit)

**Comment by tmckayus** [comment]
Assuming we do that stuff ^^, we should probably at least sync this commit with one to add a build-job template to take the place of dc batch without continuous relaunch

**Comment by elmiko** [comment]
i've got a similar change on the java template here as well,  #37 

so, if we back-port, we should catch that too

**Comment by tmckayus** [comment]
@matt, okay, so what's our stance in the meantime for batch with an s2i image?  Use separate build and job templates (which we have already) for a two step?  Copy and modify the template for an app-exit=false use case?

this change is certainly the right solution for a streaming app through s2i, imho

**Comment by tmckayus** [comment]
We should keep the standalone template set in sync with resources.yaml. Anything we do here should be reflected in the other files (note to self)

**Comment by mattf** [comment]
my stance is to let adanced users/oshinko hackers use the oshinko-s2i repo templates and we promote them here when they're ready

**Pull request merged**
