### PR TITLE
change s3 example to use external repo

### PR DESCRIPTION
**Pull request by elmiko**
This change removes the s3 notebook file from the assets and changes the
documentation links to reference an external github project.

### CODE REVIEW

**Comment by elmiko** [comment]
@tmckayus @mattf ptal

**Comment by mattf** [comment]
my 2c is to keep its life linked to the example on the site.

**Comment by elmiko** [comment]
i don't mind keeping it that way, but i think we should bring this example http://radanalytics.io/applications/pyspark_hdfs_notebook to live on the site as well. if we are going to house a bunch of notebook examples here, then i'd like to try and keep it consistent.

**Comment by tmckayus** [comment]
agreed on that last point, Mike.  We should converge. Part of this hinges on whether we supply just a notebook file to upload, or an image with the notebook embedded, or both.  Image/both suggests an external repo (unless we put the dockerfile etc under assets too)

**Comment by elmiko** [comment]
i like the distinction you are drawing Trevor, like if we have external repos that can build to a notebook that's one thing, but if we decide to just have the generic notebook image that can load notebooks then it makes much more sense to house all of them together.

**Comment by elmiko** [comment]
i'm going to close this and look towards bringing the other notebooks back to the site

**Pull request closed without merging**
