### PR TITLE
add how do i page

### PR DESCRIPTION
**Pull request by elmiko**
Changes
* add howdoi to config
* add howdoi to menu
* add howdoi template
* remove how to faqs
* add how to from faqs to howdoi
* change default layout to add list expansion code

### CODE REVIEW

**Comment by elmiko** [comment]
@mattf @willb @tmckayus ptal

this makes a larger change to the menu and adds a new sections, i'd like a few more eyeballs before merging

**Comment by willb** [comment]
lgtm, thanks Mike!

**Comment by tmckayus** [comment]
lgtm too!

**Comment by elmiko** [comment]
thanks guys

**Pull request merged**
