### PR TITLE
Add talk: Apache Spark for Library Developers

### PR DESCRIPTION
**Pull request by erikerlandson**

### CODE REVIEW

**Comment by erikerlandson** [comment]
There is a problem here: there were two separate videos. I tried adding two media entries but it just renders the second one (Will's vid does not show on the site)

**Comment by willb** [comment]
Let’s add it as two talks and cross-reference them.

**Comment by elmiko** [comment]
the template mechanism is currently set to only take 1 media link. let me look at expanding that, i don't think we've had a presentation with multiple video links before.

**Comment by elmiko** [comment]
so, a quick look at the templates makes me think we could add an array value for the media link, then it would be easy to handle this situation.

i can cook up a pr to add this, i just need to make a few modifications.

**Comment by erikerlandson** [comment]
I don't have strong feelings about the SF single-session. Maybe keep it as an abridged version?

**Comment by erikerlandson** [comment]
on reflection, I think I like the idea of keeping the shorter June version too

**Comment by erikerlandson** [comment]
[update rad.io with spark talks](https://trello.com/c/XIHxUIEu/750-update-radio-with-spark-talks)

**Comment by willb** [comment]
We had discussed keeping only one version of each talk earlier this year but I’m not starting a fight.  It’s probably a good idea to cross-reference the alternate in each if we keep both.

**Comment by erikerlandson** [comment]
Oh, I see. Sure, I'll take it out

**Comment by erikerlandson** [comment]
Is this good to merge?

**Comment by elmiko** [comment]
i'm good if you guys are

**Pull request merged**
