### PR TITLE
Add a script to generate a resources.yaml referencing tagged images

### PR DESCRIPTION
**Pull request by tmckayus**

### CODE REVIEW

**Comment by tmckayus** [comment]
Note, this is a convenience for testing/developing using resources.yaml.

Considering https://github.com/radanalyticsio/radanalyticsio.github.io/pull/113, the sed commands would change slightly, for example

sed -r -i "s@(radanalyticsio/radanalytics.*spark)(:stable)@\1:$1@" $TOP_DIR/release_templates/*

**Comment by elmiko** [comment]
should we wait to merge and update this to match #113 ?

**Comment by tmckayus** [comment]
@elmiko, yes

**Comment by elmiko** [comment]
if we're going to put this in the root of the project, we should add an exclude line to the _config.yml so that it doesn't get rendered to the output.

**Comment by tmckayus** [comment]
Closing this and moving the script with mods to https://github.com/radanalyticsio/oshinko-release/pull/2

**Pull request closed without merging**
