### PR TITLE
add global resources.yaml to help install/setup and update getting started to use it

### PR DESCRIPTION
**Pull request by mattf**
@elmiko ptal

### CODE REVIEW

**Comment by mattf** [comment]
@tmckayus ptal

**Comment by elmiko** [comment]
this looks good at first glance, i'd like to make a `downloads` directory, or similar, and add the yaml file there instead of the root dir. that's my only comment currently.

**Comment by mattf** [comment]
hmm, this file isn't really something a user would download as much as load into an openshift deployment.

ok with merging and working out some sort of download option later, maybe when we have pointers to the cli download artifacts?

**Comment by elmiko** [comment]
my only concern was not putting a bunch of stuff in the root dir. i'm ok to merge and just make another directory later, it's not very complicated we just need to make a directory and move the file.

**Pull request merged**
